In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("../data/telco_churn_cleaned.csv")

In [3]:
df.shape

(7043, 21)

In [4]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.50,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
df.columns.tolist()

['customerID',
 'gender',
 'SeniorCitizen',
 'Partner',
 'Dependents',
 'tenure',
 'PhoneService',
 'MultipleLines',
 'InternetService',
 'OnlineSecurity',
 'OnlineBackup',
 'DeviceProtection',
 'TechSupport',
 'StreamingTV',
 'StreamingMovies',
 'Contract',
 'PaperlessBilling',
 'PaymentMethod',
 'MonthlyCharges',
 'TotalCharges',
 'Churn']

In [6]:
df['TotalCharges'] = pd.to_numeric(
    df['TotalCharges'],
    errors='coerce'
)

In [7]:
df['TotalCharges'].isnull().sum()

np.int64(0)

In [8]:
df['avg_monthly_spend'] = (
    df['TotalCharges'] /
    df['tenure'].replace(0, 1)
)

In [9]:
df[
    ['tenure', 'TotalCharges',
     'MonthlyCharges', 'avg_monthly_spend']
].head(10)

   tenure  TotalCharges  MonthlyCharges  avg_monthly_spend
0       1         29.85           29.85          29.850000
1      34       1889.50           56.95          55.573529
2       2        108.15           53.85          54.075000
3      45       1840.75           42.30          40.905556
4       2        151.65           70.70          75.825000
5       8        820.50           99.65         102.562500
6      22       1949.40           89.10          88.609091
7      10        301.90           29.75          30.190000
8      28       3046.05          104.80         108.787500
9      62       3487.95           56.15          56.257258

Featurer 2

In [10]:
df['charge_diff'] = (
    df['MonthlyCharges'] -
    df['avg_monthly_spend']
)

In [11]:
df[
    ['MonthlyCharges',
     'avg_monthly_spend',
     'charge_diff']
].head(10)

   MonthlyCharges  avg_monthly_spend  charge_diff
0           29.85          29.850000     0.000000
1           56.95          55.573529     1.376471
2           53.85          54.075000    -0.225000
3           42.30          40.905556     1.394444
4           70.70          75.825000    -5.125000
5           99.65         102.562500    -2.912500
6           89.10          88.609091     0.490909
7           29.75          30.190000    -0.440000
8          104.80         108.787500    -3.987500
9           56.15          56.257258    -0.107258

Feature 3

In [12]:
def tenure_group(t):
    if t <= 12:
        return 'New (0-1yr)'
    elif t <= 48:
        return 'Mid (1-4yr)'
    else:
        return 'Loyal (4yr+)'

In [13]:
df['tenure_group'] = df['tenure'].apply(tenure_group)

In [14]:
df['tenure_group'].value_counts()

tenure_group
Mid (1-4yr)     2618
Loyal (4yr+)    2239
New (0-1yr)     2186
Name: count, dtype: int64

In [15]:
df[['tenure', 'tenure_group']].head(20)

    tenure  tenure_group
0        1   New (0-1yr)
1       34   Mid (1-4yr)
2        2   New (0-1yr)
3       45   Mid (1-4yr)
4        2   New (0-1yr)
5        8   New (0-1yr)
6       22   Mid (1-4yr)
7       10   New (0-1yr)
8       28   Mid (1-4yr)
9       62  Loyal (4yr+)
10      13   Mid (1-4yr)
11      16   Mid (1-4yr)
12      58  Loyal (4yr+)
13      49  Loyal (4yr+)
14      25   Mid (1-4yr)
15      69  Loyal (4yr+)
16      52  Loyal (4yr+)
17      71  Loyal (4yr+)
18      10   New (0-1yr)
19      21   Mid (1-4yr)

Feature 4

In [16]:
service_cols = [
    'OnlineSecurity',
    'OnlineBackup',
    'DeviceProtection',
    'TechSupport',
    'StreamingTV',
    'StreamingMovies'
]

In [17]:
df['service_count'] = (
    df[service_cols] == 'Yes'
).sum(axis=1)

In [18]:
df[
    ['service_count'] + service_cols
].head(10)

,service_count,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies
0,1,No,Yes,No,No,No,No
1,2,Yes,No,Yes,No,No,No
2,2,Yes,Yes,No,No,No,No
3,3,Yes,No,Yes,Yes,No,No
4,0,No,No,No,No,No,No
5,3,No,No,Yes,No,Yes,Yes
6,2,No,Yes,No,No,Yes,No
7,1,Yes,No,No,No,No,No
8,4,No,No,Yes,Yes,Yes,Yes
9,2,Yes,Yes,No,No,No,No

In [19]:
df[
    [
        'avg_monthly_spend',
        'charge_diff',
        'tenure_group',
        'service_count'
    ]
].head(10)

   avg_monthly_spend  charge_diff  tenure_group  service_count
0          29.850000     0.000000   New (0-1yr)              1
1          55.573529     1.376471   Mid (1-4yr)              2
2          54.075000    -0.225000   New (0-1yr)              2
3          40.905556     1.394444   Mid (1-4yr)              3
4          75.825000    -5.125000   New (0-1yr)              0
5         102.562500    -2.912500   New (0-1yr)              3
6          88.609091     0.490909   Mid (1-4yr)              2
7          30.190000    -0.440000   New (0-1yr)              1
8         108.787500    -3.987500   Mid (1-4yr)              4
9          56.257258    -0.107258  Loyal (4yr+)              2

In [20]:
df[
    [
        'avg_monthly_spend',
        'charge_diff',
        'tenure_group',
        'service_count'
    ]
].isnull().sum()

avg_monthly_spend    0
charge_diff          0
tenure_group         0
service_count        0
dtype: int64

In [21]:
df.shape

(7043, 25)

In [22]:
df.to_csv(
    "../data/telco_churn_feature_engineered.csv",
    index=False
)

In [23]:
import os

os.path.exists(
    "../data/telco_churn_feature_engineered.csv"
)

True

In [24]:
from sqlalchemy import create_engine

engine = create_engine(
    "postgresql://postgres:nitesh18@localhost:5432/telco_churn"
)

In [25]:
df.to_sql(
    'customers_feature_engineered',
    engine,
    if_exists='replace',
    index=False
)

43

In [26]:
pd.read_sql(
    "SELECT COUNT(*) FROM customers_feature_engineered",
    engine
)

   count
0   7043